[package]
name = "rectree"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/rectree"

[dependencies]
hashbrown = { version = "0.16.1", default-features = false, features = ["default-hasher", "inline-more"] }
kurbo = "0.13.0"
